services:
  mongo:
    image: mongo:latest
    container_name: hidrored-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 

    networks:
      - hidrored-net
  mongo-express:
    image: mongo-express:latest
    container_name: hidrored-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_BASICAUTH_PASSWORD=
    depends_on:
      - mongo
    networks:
      - hidrored-net

networks:
  hidrored-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local

